### ISSUE TITLE
Same names without same damage

### ISSUE THREAD

**Issue by Godivctor** [NexAdn/UnitedShops#16]
When set to buy two materials with the same name but without same damage the shop only show to buy the material with higher damage.
Example:
```
STONE:
   buy: 10
   sell: 5
   damage: 0
STONE:
   buy: 10
   sell: 5
   damage: 1
```
Only the STONE with damage 1 show to buy.
